// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypahgbzlatigjgykvccb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwYWhnYnpsYXRpZ2pneWt2Y2NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTc5NjQsImV4cCI6MjA3MDAzMzk2NH0.ywFv6CD66s9h6UGdScvIiCIJ8O_dRTDaJyVhpR1VwIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});